server:
  port: 10010
spring:
  application:
    name: cloudstorage-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
zuul:
  prefix: /api
  routes:
    item-service: /item/** # 商品微服务路由
  add-host-header: true
  sensitive-headers:  # 覆盖敏感头信息，使cookie可以正常写入